import {
  getEmployeesRequest,
  getUniqueEmployeesRequest,
  createEmployeeRequest,
  editEmployeesRequest,
  deleteEmployeesRequest
} from './thunks';
import {
  GET_EMPLOYEES_SUCCESS,
  GET_EMPLOYEES_PENDING,
  GET_EMPLOYEES_ERROR,
  GET_EMPLOYEES,
  GET_UNIQUE_EMPLOYEES_SUCCESS,
  GET_UNIQUE_EMPLOYEES_PENDING,
  GET_UNIQUE_EMPLOYEES_ERROR,
  GET_UNIQUE_EMPLOYEE,
  CREATE_EMPLOYEES_SUCCESS,
  CREATE_EMPLOYEES_PENDING,
  CREATE_EMPLOYEES_ERROR,
  CREATE_EMPLOYEE,
  EDIT_EMPLOYEES_SUCCESS,
  EDIT_EMPLOYEES_PENDING,
  EDIT_EMPLOYEES_ERROR,
  EDIT_EMPLOYEE,
  DELETE_EMPLOYEES_SUCCESS,
  DELETE_EMPLOYEES_PENDING,
  DELETE_EMPLOYEES_ERROR,
  DELETE_EMPLOYEE
} from './constants';
