export const GET_TIMESHEETS_PENDING = 'GET_TIMESHEETS_PENDING';
export const GET_TIMESHEETS_SUCCESS = 'GET_TIMESHEETS_SUCCESS';
export const GET_TIMESHEETS_ERROR = 'GET_TIMESHEETS_ERROR';
export const DELETE_TIMESHEETS_PENDING = 'DELETE_TIMESHEETS_PENDING';
export const DELETE_TIMESHEETS_SUCCESS = 'DELETE_TIMESHEETS_SUCCESS';
export const DELETE_TIMESHEETS_ERROR = 'DELETE_TIMESHEETS_ERROR';
