export const ADD_TIMESHEET_PENDING = 'ADD_TIMESHEET_PENDING';
export const ADD_TIMESHEET_SUCCESS = ' ADD_TIMESHEET_SUCCESS';
export const ADD_TIMESHEET_ERROR = ' ADD_TIMESHEET_ERROR';
export const EDIT_TIMESHEET_PENDING = 'EDIT_TIMESHEET_PENDING';
export const EDIT_TIMESHEET_SUCCESS = ' EDIT_TIMESHEET_SUCCESS';
export const EDIT_TIMESHEET_ERROR = ' EDIT_TIMESHEET_ERROR';
