export const GET_TIMESHEET_PENDING = 'GET_TIMESHEET_PENDING';
export const GET_TIMESHEET_SUCCESS = 'GET_TIMESHEET_SUCCESS';
export const GET_TIMESHEET_ERROR = 'GET_TIMESHEET_ERROR';
export const DELETE_TIMESHEET_PENDING = 'DELETE_TIMESHEET_PENDING';
export const DELETE_TIMESHEET_SUCCESS = 'DELETE_TIMESHEET_SUCCESS';
export const DELETE_TIMESHEET_ERROR = 'DELETE_TIMESHEET_ERROR';
export const RESET_TIMESHEET = 'RESET_TIMESHEET';
export const RESET_MESSAGE = 'RESET_MESSAGE';
