export const GET_TIMESHEETS_BY_EMPLOYEE_PENDING = 'GET_TIMESHEETS_BY_EMPLOYEE_PENDING';
export const GET_TIMESHEETS_BY_EMPLOYEE_SUCCESS = 'GET_TIMESHEETS_BY_EMPLOYEE_SUCCESS';
export const GET_TIMESHEETS_BY_EMPLOYEE_ERROR = 'GET_TIMESHEETS_BY_EMPLOYEE_ERROR';
export const RESET_MESSAGE = 'RESET_MESSAGE';
